### ISSUE TITLE
Remove title of app-section in navigation bar

### ISSUE THREAD

**Issue by MarE1991** [noi-techpark/it.bz.noi.community.ios#51]
Please remove the title of App-Section in the Navigation bar.
![image](https://user-images.githubusercontent.com/92152188/136956021-52da6d6e-c68b-4eeb-b5a0-f45e72b853d5.png)

German Version
Device used: iPhone11 | iOS 15.0.1 | App Version: 1.0 (202110071816000)

**Comment by pkritzinger** [comment]
@matax87 @macteo 

> (i.e. Meet up! in the example which is a copy text that you choose).

Definitely correct. We did not foresee to use the same wording as in the bottom nav bar. That is why it would make it easier to hide the title in the back-nav.

> I think that Instagram and other major apps have a complex navigation and they took the shortcut and removed any back titles. On the other hand, the NOI-Community app has a simple navigation at this time.

For now yes. But we do not know how complex the navigation structure will become in future. So why accustom the user to sth. we might remove in future? 

> If I may suggest Instagram & co must not be taken as examples of good/best practices in UX/etc. since people are inclined to use them anyway; and this is not the same for an app like NOI-Community.

I don't understand this argumentation. 
Anyways, Instagram & Co are - at least in my opinion - players that shape user behaviour, user expectations and requirements. Since they don't use the title in the back-navigation it is - again in my opinion - not something a user would heavily miss.

**Comment by Piiit** [comment]
@sseppi @pkritzinger Has the title been removed? If yes, I would close this issue and create new user stories for a new dev cycle... otherwise it might get overcomplicated to discuss things that are not strictly related to the title of this issue... ok?

**Comment by pkritzinger** [comment]
@Piiit : no, title is still included.

**Comment by Piiit** [comment]
OK, then lets keep it open and in backlog for this cycle

**Comment by Piiit** [comment]
@pkritzinger Please test and eventually close this issue
