### ISSUE TITLE
Section "More" - list view and title

### ISSUE THREAD

**Issue by MarE1991** [noi-techpark/it.bz.noi.community.ios#57]
More

- [ ] It would be great if the list view would reflect the design (same as “Meet”).

- [ ] Please remove the “More”-Title in the section. Screenshot design: [prntscr.com/1vtgbet](url) vs. App: [prntscr.com/1vtgdtn](url)

German version
Device used: iPhone11 | iOS 15.0.1 | App Version: 1.0 (202110071816000)

**Comment by dev4dimension** [comment]
@MarE1991 it's not really "usual" to have a design like the proposed one, without a title/navigation bar, mostly because this page has tappable elements that push to a new view (with a navigation bar for the back button). Also a title is needed for accessible reasons (it's the first thing a screen reader read). And also, the title/navigation is present in coherence with the other pages (es. the home) who has a title. 

For that reasons we highly raccomando to keep it like we made it.

**Comment by MarE1991** [comment]
@pkritzinger

**Comment by Piiit** [comment]
@MarE1991 Feel free to close it, if you are happy with the result... I merged the corresponding code changes, the new release should be out soon

**Comment by Piiit** [comment]
@MarE1991 Can we close this?

**Comment by Piiit** [comment]
@MarE1991 @macteo @ddalledo Closing for now, we postpone future development to the next dev cycle
